### ISSUE TITLE
[Question] a way to clean the terminal?

### ISSUE THREAD

**Issue by RicardoRien** [akinsho/toggleterm.nvim#176]
There is a way to clean the terminal? 'Ctrl + l' doesn't work, just close the terminal.
Or better, a way to auto clean the terminal every time I close it

**Comment by akinsho** [comment]
@RicardoRien this is something that can be solved in your shell rc file i.e. your `.bashrc` or `.zshrc` this isn't really an issue for this plugin. I'm sure solutions exist for that on stack but it's not something I'd implement in this plugin

**Comment by akinsho** [comment]
Going to close this out since as I mentioned I believe this is a problem best solved at the rc file level rather than with a neovim plugin where frankly it can't really be solved anyway

**Comment by nitaicharan** [comment]
I'd like how to do it @akinsho . I still have a problem with it and i couldn't find a way to solve it.
